<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspañoles [
  <!ELEMENT reyesEspañoles (rey* | reina*)*>
  <!ELEMENT rey (nombre, padre, madre)>
  <!ELEMENT reina (nombre, padre, madre)>
          <!ATTLIST reina codigo ID #REQUIRED>  
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT padre (#PCDATA)>
  <!ELEMENT madre (#PCDATA)>
            <!ATTLIST madre referencia IDREF #IMPLIED>  
  
]>

<reyesEspañoles>
  <rey>
    <nombre>Felipe III</nombre>
    <padre>Felipe II</padre>
    <madre>Ana de Austria</madre>
  </rey>
  <reina codigo="juana_la_loca">
    <nombre>Juana la Loca</nombre>
    <padre>Fernando el Católico</padre>
    <madre>Isabel la Católica</madre>
  </reina>
  <rey>
    <nombre>Carlos I</nombre>
    <padre>Felipe el Hermoso</padre>
    <madre referencia="juana_la_loca">Juan la Loca</madre>
  </rey>
</reyesEspañoles>