=== AsunAlvarez/lenguaje_marcas/XML/examen/EXAMEN/2.dtd
<!ELEMENT toolbox (menubar*)>
          <!ATTLIST toolbox
                    flex (1|0) #REQUIRED>
<!ELEMENT menubar (menu*)>
<!ELEMENT menu (menupopup)>
        <!ATTLIST menu
                  label NMTOKENS #REQUIRED>
<!ELEMENT menupopup (menuitem* | menuseparator*)*>
<!ELEMENT menuitem (#PCDATA)>
  <!ATTLIST menuitem
            label NMTOKENS #REQUIRED>
<!ELEMENT menuseparator (#PCDATA)>

=== AsunAlvarez/lenguaje_marcas/XML/examen/EXAMEN/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbox SYSTEM "C:/Users/Javier/Desktop/$$_DAW/Lenguaje_Marcas/XML/examen/EXAMEN/2.dtd">
<toolbox flex="1">
<menubar>
      <menu label="Archivo">
            <menupopup>
                  <menuitem label="Abrir"></menuitem>         
                  <menuitem label="Cerrar"></menuitem>
                  <menuseparator></menuseparator>
                  <menuitem label="Salir"></menuitem>    
            </menupopup>      
      </menu>
      <menu label="Ayuda">
            <menupopup>
                  <menuitem label="Manual"></menuitem>         
            </menupopup>      
      </menu>

</menubar>


</toolbox>
